/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: fngagltbIx1HL3w3KIy9R0lpIHqlxgFQMHd4pwrcKcpGgDh/2GttgDTeQFpbiCF7j8RpovvMC82LlhKMfTLlmw==
 */

/* eslint-disable */
// tslint:disable

interface Accounts {
  account_number: number & {readonly __brand?: 'accounts_account_number'}
  amount: number
  credit_limit: (number) | null
  name: string
  type: string
}
export default Accounts;

interface Accounts_InsertParameters {
  account_number: number & {readonly __brand?: 'accounts_account_number'}
  amount: number
  credit_limit?: (number) | null
  name: string
  type: string
}
export type {Accounts_InsertParameters}
