/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: nVREv7dBL/NiuXOuZ+xgtVjWbevrOGgLbZeGtKHmGAXHHnmL+u7F+yMu9rUWEXGn7BUcjWpp3hcByIUZyygCeQ==
 */

/* eslint-disable */
// tslint:disable

import Accounts, {Accounts_InsertParameters} from './accounts'

interface DatabaseSchema {
  accounts: {record: Accounts, insert: Accounts_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  Accounts,
  Accounts_InsertParameters,
}
